name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is this related to a frustration with the current behavior?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like syslua to...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Example API / Usage
      description: If applicable, show how the feature would be used in a config.
      render: lua
      placeholder: |
        -- Example usage
        sys.build({
          -- ...
        })
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What area does this feature affect?
      options:
        - CLI commands
        - Lua API (sys.build, sys.bind, etc.)
        - Modules (file, env, etc.)
        - Store / caching
        - Snapshots / rollback
        - Cross-platform support
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples that help explain the feature.
      placeholder: Add any other context here...
    validations:
      required: false
